language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
- gemfiles/Gemfile.rubocop-old
- gemfiles/Gemfile.rubocop-next
script:
  - bundle exec rspec spec
jobs:
  include:
    - stage: Lint Ruby
      gemfile: Gemfile
      script: bundle exec rubocop